version: '3.1'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/projects"
    tty: true
    
    # -i: API仕様ファイル
    # -s: プレビューサーバー起動
    # -h: プレビューサーバーをバインドするためのアドレス
    command: aglio -i ./md/user-api.md -s -h 0.0.0.0
